import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Url Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="min-h-screen flex justify-center items-center gap-x-4">
          <Link
            href="/Register"
            className="px-6 py-3 bg-indigo-400 text-gray-100 rounded-3xl"
          >
            Register
          </Link>
          <Link
            href="/Login"
            className="px-6 py-3 bg-indigo-400 text-gray-100 rounded-3xl"
          >
            Log in
          </Link>
        </section>
      </main>
    </>
  );
}
